package io.webrpc.client

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.decodeFromString
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encodeToString
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonElement

import kotlinx.coroutines.CancellationException
import java.io.IOException
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody

// node-ts v1.0.0 906081878510a249f51ad6cea52296d56fe2685b
// --
// Code generated by webrpc-gen@v0.37.1 with .. generator. DO NOT EDIT.
//
// webrpc-gen -schema=../_examples/ClientExample/service.ridl -target=.. -client -okhttpTransport=true -out=../_examples/ClientExample/client/src/main/kotlin/ExampleServiceClient.kt

// WebRPC description and code-gen version
const val WEBRPC_VERSION = "v1"

// Schema version of your RIDL schema
const val WEBRPC_SCHEMA_VERSION = "v1.0.0"

// Schema hash generated from your RIDL schema
const val WEBRPC_SCHEMA_HASH = "906081878510a249f51ad6cea52296d56fe2685b"

// region Types


typealias Username = String



typealias Age = UInt



@Serializable(with = KindSerializer::class)
enum class Kind(val wireValue: String) {
    USER("USER"),
    ADMIN("ADMIN"),
    UNKNOWN_DEFAULT("UNKNOWN_DEFAULT");

    companion object {
        fun fromWireValue(value: String): Kind {
            return values().find { it.wireValue == value } ?: UNKNOWN_DEFAULT
        }
    }
}

object KindSerializer : KSerializer<Kind> {
    override val descriptor: SerialDescriptor =
        String.serializer().descriptor

    override fun serialize(encoder: Encoder, value: Kind) {
        encoder.encodeSerializableValue(
            String.serializer(),
            value.wireValue,
        )
    }

    override fun deserialize(decoder: Decoder): Kind {
        return Kind.fromWireValue(
            decoder.decodeSerializableValue(
                String.serializer(),
            ),
        )
    }
}



@Serializable
data class User(
    @SerialName("id")
    val id: ULong,
    @SerialName("USERNAME")
    val username: String,
    @SerialName("role")
    val role: Kind,
    @SerialName("meta")
    val meta: Map<String, JsonElement>,
    @SerialName("createdAt")
    val createdAt: String? = null,
)



@Serializable
data class Page(
    @SerialName("num")
    val num: UInt,
)



// endregion


// region Runtime
val WebRpcJson: Json = Json {
    ignoreUnknownKeys = true
}

data class WebRpcHttpResponse(
    val statusCode: Int,
    val body: String,
    val headers: Map<String, String> = emptyMap(),
)

interface WebRpcTransport {
    suspend fun post(
        baseUrl: String,
        path: String,
        body: String,
        headers: Map<String, String> = emptyMap(),
    ): WebRpcHttpResponse
}

class WebRpcTransportException(
    message: String,
    cause: Throwable? = null,
) : IOException(message, cause)
class OkHttpWebRpcTransport(
    private val okHttpClient: OkHttpClient = OkHttpClient(),
) : WebRpcTransport {
    override suspend fun post(
        baseUrl: String,
        path: String,
        body: String,
        headers: Map<String, String>,
    ): WebRpcHttpResponse = withContext(Dispatchers.IO) {
        val request = Request.Builder()
            .url(joinUrl(baseUrl, path))
            .post(body.toRequestBody(jsonMediaType))
            .apply {
                headers.forEach { (name, value) -> addHeader(name, value) }
            }
            .build()

        try {
            okHttpClient.newCall(request).execute().use { response ->
                val responseBody = response.body?.string().orEmpty()
                val responseHeaders = response.headers.toMultimap()
                    .mapValues { (_, values) -> values.lastOrNull().orEmpty() }
                WebRpcHttpResponse(
                    statusCode = response.code,
                    body = responseBody,
                    headers = responseHeaders,
                )
            }
        } catch (exception: IOException) {
            throw WebRpcTransportException("WebRPC HTTP request failed", exception)
        }
    }

    companion object {
        private val jsonMediaType = "application/json; charset=utf-8".toMediaType()
    }
}

private fun joinUrl(baseUrl: String, path: String): String =
    baseUrl.trimEnd('/') + "/" + path.trimStart('/')

suspend inline fun <O> executeWebRpc(
    baseUrl: String,
    urlPath: String,
    body: String,
    transport: WebRpcTransport,
    headers: Map<String, String> = emptyMap(),
    json: Json = WebRpcJson,
    crossinline decodeSuccess: (body: String, json: Json) -> O,
): O {
    val response = try {
        transport.post(
            baseUrl = baseUrl,
            path = urlPath,
            body = body,
            headers = headers,
        )
    } catch (e: CancellationException) {
        throw e
    } catch (e: WebRpcTransportException) {
        throw e
    } catch (e: Throwable) {
        throw WebRpcTransportException("WebRPC request failed", e)
    }

    if (response.statusCode !in 200..299) {
        throw decodeWebRpcError(response.statusCode, response.body, json)
    }

    return decodeSuccess(response.body, json)
}
// endregion

// region Errors
enum class ErrorKind(val code: Int) {
    WEBRPC_ENDPOINT(0),
    WEBRPC_REQUEST_FAILED(-1),
    WEBRPC_BAD_ROUTE(-2),
    WEBRPC_BAD_METHOD(-3),
    WEBRPC_BAD_REQUEST(-4),
    WEBRPC_BAD_RESPONSE(-5),
    WEBRPC_SERVER_PANIC(-6),
    WEBRPC_INTERNAL_ERROR(-7),
    WEBRPC_CLIENT_ABORTED(-8),
    WEBRPC_STREAM_LOST(-9),
    WEBRPC_STREAM_FINISHED(-10),
    UNKNOWN(-999);

    companion object {
        fun fromCode(code: Int): ErrorKind {
            return ErrorKind.values().find { it.code == code } ?: UNKNOWN
        }
    }
}

data class WebRpcError(
    val error: String,
    val code: Int,
    override val message: String,
    val causeString: String,
    val status: Int,
    val errorKind: ErrorKind = ErrorKind.fromCode(code),
) : Exception(message)

@Serializable
private data class WebRpcErrorPayload(
    @SerialName("error") val error: String? = null,
    @SerialName("code") val code: Int? = null,
    @SerialName("msg") val message: String? = null,
    @SerialName("cause") val causeString: String? = null,
    @SerialName("status") val status: Int? = null,
)

fun decodeWebRpcError(
    statusCode: Int,
    body: String,
    json: Json = WebRpcJson,
): WebRpcError {
    return try {
        val payload = json.decodeFromString<WebRpcErrorPayload>(body)
        val code = payload.code ?: ErrorKind.UNKNOWN.code
        WebRpcError(
            error = payload.error ?: "WebrpcEndpoint",
            code = code,
            message = payload.message ?: "endpoint error",
            causeString = payload.causeString.orEmpty(),
            status = payload.status ?: statusCode,
            errorKind = ErrorKind.fromCode(code),
        )
    } catch (_: Throwable) {
        WebRpcError(
            error = "WebrpcBadResponse",
            code = ErrorKind.UNKNOWN.code,
            message = "Unable to decode error response",
            causeString = body,
            status = statusCode,
            errorKind = ErrorKind.UNKNOWN,
        )
    }
}
// endregion

// region Service Metadata
object ExampleServiceApi {
    const val basePath: String = "/v1/ExampleService"

    object Ping {
        const val path: String = "/Ping"
        const val urlPath: String = "/v1/ExampleService/Ping"
        @Suppress("UNUSED_PARAMETER")
        fun encodeRequest(json: Json = WebRpcJson): String {
            return "{}"
        }

        @Suppress("UNUSED_PARAMETER")
        fun decodeResponse(body: String, json: Json = WebRpcJson) {
            return
        }
    }

    object GetUser {
        const val path: String = "/GetUser"
        const val urlPath: String = "/v1/ExampleService/GetUser"

        @Serializable
        data class Request(
            @SerialName("userID")
            val userId: ULong,
        )

        @Serializable
        data class Response(
            @SerialName("code")
            val code: UInt,
            @SerialName("user")
            val user: User,
        )
        fun encodeRequest(request: Request, json: Json = WebRpcJson): String {
            return json.encodeToString(request)
        }

        fun decodeResponse(body: String, json: Json = WebRpcJson): Response {
            return json.decodeFromString(body)
        }
    }
}

class ExampleServiceClient(
    private val baseUrl: String,
    private val transport: WebRpcTransport,
    private val json: Json = WebRpcJson,
    private val headers: () -> Map<String, String> = { emptyMap() },
) {

    @Throws(WebRpcError::class, WebRpcTransportException::class)
    suspend fun ping() {
        return executeWebRpc(
            baseUrl = baseUrl,
            urlPath = ExampleServiceApi.Ping.urlPath,
            body = ExampleServiceApi.Ping.encodeRequest(json),
            transport = transport,
            headers = headers(),
            json = json,
            decodeSuccess = { body, decodeJson ->
                ExampleServiceApi.Ping.decodeResponse(body, decodeJson)
            },
        )
    }

    @Throws(WebRpcError::class, WebRpcTransportException::class)
    suspend fun getUser(request:ExampleServiceApi.GetUser.Request): ExampleServiceApi.GetUser.Response {
        return executeWebRpc(
            baseUrl = baseUrl,
            urlPath = ExampleServiceApi.GetUser.urlPath,
            body = ExampleServiceApi.GetUser.encodeRequest(request, json),
            transport = transport,
            headers = headers(),
            json = json,
            decodeSuccess = { body, decodeJson ->
                ExampleServiceApi.GetUser.decodeResponse(body, decodeJson)
            },
        )
    }
}
// endregion

