package io.webrpc.client

import com.squareup.moshi.*
import java.time.OffsetDateTime

import com.squareup.moshi.JsonReader.Token
import com.squareup.moshi.adapters.EnumJsonAdapter
import com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory
import java.time.format.DateTimeFormatter
import io.ktor.client.*
import io.ktor.client.plugins.logging.*
import io.ktor.client.request.*
import io.ktor.client.statement.*
import io.ktor.http.*
import io.ktor.http.parsing.*
import java.lang.reflect.Type
import kotlin.coroutines.cancellation.CancellationException

// node-ts v1.0.0 abe85e3ae75b05e37b853350e9fc16e17dc75b42
// --
// Code generated by webrpc-gen@v0.32.3 with ../../ generator. DO NOT EDIT.
//
// webrpc-gen -schema=service.ridl -target=../../ -client -out=client/src/main/kotlin/ExampleServiceClient.kt

// WebRPC description and code-gen version
const val WEBRPC_VERSION = "v1"

// Schema version of your RIDL schema
const val WEBRPC_SCHEMA_VERSION = "v1.0.0"

// Schema hash generated from your RIDL schema
const val WEBRPC_SCHEMA_HASH = "abe85e3ae75b05e37b853350e9fc16e17dc75b42"

// region Types
@JsonClass(generateAdapter = true)
enum class Kind {
    @Json(name = "USER")
    USER,
    @Json(name = "ADMIN")
    ADMIN,
    @Json(name = "UNKNOWN_DEFAULT")
    UNKNOWN_DEFAULT,
}

@JsonClass(generateAdapter = true)
data class User(
    @Json(name = "id") val id: ULong,
    @Json(name = "USERNAME") val username: String,
    @Json(name = "role") val role: Kind,
    @Json(name = "meta") val meta: Map<String, Any>,
    @Json(name = "createdAt") val createdAt: OffsetDateTime?,
)

@JsonClass(generateAdapter = true)
data class Page(
    @Json(name = "num") val num: UInt,
)
// endregion




// region Client
interface ExampleService {
    @Throws(WebRpcError::class)
    suspend fun ping()
    @Throws(WebRpcError::class)
    suspend fun getUser(userId: ULong): ExampleService.GetUserResponse

    data class GetUserRequest(
        @Json(name = "userID") val userId: ULong,
    )

    data class GetUserResponse(
        @Json(name = "code") val code: UInt,
        @Json(name = "user") val user: User,
    )
}

open class WebRpcKtorClient {
    @Suppress("RethrowCaughtException")
    @Throws(WebRpcError::class)
    protected suspend inline fun <reified I, reified O> request(
        client: HttpClient,
        baseUrl: String,
        method: String,
        body: I?,
        serialize: (I) -> String,
        deserialize: (String) -> O,
        deserializeError: (String) -> WebRpcError,
        extraHttpBuilder: HttpRequestBuilder.() -> Unit = {},
    ): O {
        return try {
            val response = client.post(baseUrl) {
                url {
                    appendPathSegments(method)
                }
                contentType(ContentType.Application.Json)
                setBody(body?.let { serialize(body) } ?: "{}")
                extraHttpBuilder()
            }

            val responseBody = response.bodyAsText(fallbackCharset = Charsets.UTF_8)

            if (response.status.isSuccess()) {

                if (O::class.java != Unit::class.java) {
                    deserialize(responseBody)
                } else Unit as O

            } else {
                throw deserializeError(responseBody)
            }

        } catch (e: CancellationException) {
            // CancellationException must be propagated to ensure correct cancellation of coroutines
            throw e
        } catch (e: WebRpcError) {
            // Propagate original WebRpcError out of the function
            throw e
        } catch (e: Throwable) {
            throw createUnknownError(exception = e)
        }
    }

    protected fun createUnknownError(exception: Throwable? = null) = WebRpcError(
        error = "Unknown error",
        code = ErrorKind.UNKNOWN.code,
        message = exception?.message ?: "",
        causeString = exception?.cause?.toString() ?: "",
        status = ErrorKind.UNKNOWN.code,
        errorKind = ErrorKind.UNKNOWN,
        cause = exception,
    )
}

private object Serializer {
    @JvmStatic
    val moshiBuilder: Moshi.Builder = SerializerHelper.addEnumUnknownDefaultCase(Moshi.Builder())
}

private object SerializerHelper {
    fun addEnumUnknownDefaultCase(moshiBuilder: Moshi.Builder): Moshi.Builder {
        return moshiBuilder
            .add(
                Kind::class.java,
                EnumJsonAdapter.create(Kind::class.java).withUnknownFallback(Kind.UNKNOWN_DEFAULT).nullSafe(),
            ).add(UnsignedNumberJsonAdapter.Factory)
            .add(IsoDateAdapter())
            .addLast(KotlinJsonAdapterFactory())
    }
}

private class UnsignedNumberJsonAdapter<UnsignedT : Any> private constructor(
    private val toUnsignedT: ULong.() -> UnsignedT,
) : JsonAdapter<UnsignedT>() {
    override fun toJson(writer: JsonWriter, value: UnsignedT?) {
        when (value) {
            null -> writer.nullValue()
            else -> writer.valueSink().use { it.writeUtf8(value.toString()) }
        }
    }

    override fun fromJson(reader: JsonReader): UnsignedT? = when (val next = reader.peek()) {
        Token.NUMBER -> {
            try {
                reader.nextString().toULong().toUnsignedT()
            } catch (numberFormatException: NumberFormatException) {
                throw JsonDataException(
                    "${numberFormatException.message} for unsigned number at ${reader.path}"
                )
            }
        }

        Token.NULL -> reader.nextNull()
        else -> throw JsonDataException(
            "Expected an unsigned number but was ${reader.readJsonValue()}, " +
                    "a $next, at path ${reader.path}",
            IllegalArgumentException(next.name)
        )
    }

    object Factory : JsonAdapter.Factory {
        private val unsignedTypesMapperMap: Map<Class<*>, ULong.() -> Any> = mapOf(
            ULong::class.java to { this },
            UInt::class.java to {
                if (this > UInt.MAX_VALUE) throw NumberFormatException("Invalid number format: '$this'") else toUInt()
            },
            UShort::class.java to {
                if (this > UShort.MAX_VALUE) throw NumberFormatException("Invalid number format: '$this'") else toUShort()
            },
            UByte::class.java to {
                if (this > UByte.MAX_VALUE) throw NumberFormatException("Invalid number format: '$this'") else toUByte()
            }
        )

        private val Type.isUnsignedType: Boolean
            get() = unsignedTypesMapperMap.keys.contains(rawType)

        private val Type.mapper: ULong.() -> Any
            get() = unsignedTypesMapperMap[rawType]!!

        override fun create(
            type: Type,
            annotations: Set<Annotation>,
            moshi: Moshi,
        ): JsonAdapter<*>? = if (type.isUnsignedType) UnsignedNumberJsonAdapter(type.mapper) else null
    }
}

class IsoDateAdapter {
    @ToJson
    fun toJson(value: OffsetDateTime): String {
        return value.format(DateTimeFormatter.ISO_OFFSET_DATE_TIME)
    }

    @FromJson
    fun fromJson(value: String): OffsetDateTime {
        return OffsetDateTime.parse(value, DateTimeFormatter.ISO_OFFSET_DATE_TIME)
    }
}
    
open class ExampleServiceClient(
    baseUrl: String,
    httpClientBuilder: () -> HttpClient,
    private val httpRequestBuilder: HttpRequestBuilder.() -> Unit = {},
    moshiBuilder: Moshi.Builder = Serializer.moshiBuilder,
): WebRpcKtorClient(), ExampleService {
    private val baseUrl = baseUrl.normalizeUrl() + "/v1/ExampleService"
    private val ktorClient by lazy { httpClientBuilder() }
    private val moshi by lazy { moshiBuilder.build() }

    @Throws(WebRpcError::class)
    private suspend inline fun <reified O> request(method: String, body: Any? = null): O {
        return request(
            client = ktorClient,
            baseUrl = baseUrl,
            method = method,
            body = body,
            serialize = this::toJson,
            deserialize = { json -> fromJson(json, O::class.java) },
            deserializeError = { json -> fromJson(json, WebRpcError::class.java) },
            extraHttpBuilder = httpRequestBuilder,
        )
    }

    private fun toJson(obj: Any): String {
        return moshi.adapter(obj.javaClass).toJson(obj)
    }

    private fun <T> fromJson(json: String, type: Type): T {
        return moshi.adapter<T>(type).fromJson(json) ?: throw createUnknownError(
            ParseException("Cannot parse JSON body.", cause = IllegalStateException(json))
        )
    }

    private fun String.normalizeUrl() = this.trimEnd { it == '/' }

    @Throws(WebRpcError::class)
    override suspend fun ping() {
        request<Unit>(
            method = "Ping",
        )
    }

    @Throws(WebRpcError::class)
    override suspend fun getUser(userId: ULong): ExampleService.GetUserResponse {
        return request<ExampleService.GetUserResponse>(
            method = "GetUser",
            body = ExampleService.GetUserRequest(
                userId = userId,
            )
        )
    }
} 
// endregion

// region Errors
enum class ErrorKind(val code: Int) {
    WEBRPC_ENDPOINT(0),
    WEBRPC_REQUEST_FAILED(-1),
    WEBRPC_BAD_ROUTE(-2),
    WEBRPC_BAD_METHOD(-3),
    WEBRPC_BAD_REQUEST(-4),
    WEBRPC_BAD_RESPONSE(-5),
    WEBRPC_SERVER_PANIC(-6),
    WEBRPC_INTERNAL_ERROR(-7),
    WEBRPC_CLIENT_ABORTED(-8),
    WEBRPC_STREAM_LOST(-9),
    WEBRPC_STREAM_FINISHED(-10),
    UNKNOWN(-999);

    companion object {
        fun fromCode(code: Int): ErrorKind {
            return ErrorKind.values().find { it.code == code } ?: UNKNOWN
        }
    }
}

@JsonClass(generateAdapter = true)
data class WebRpcError(
    @Json(name = "error") val error: String,
    @Json(name = "code") val code: Int,
    @Json(name = "msg") override val message: String,
    @Json(name = "cause") val causeString: String,
    @Json(name = "status") val status: Int,
    @Transient val errorKind: ErrorKind = ErrorKind.fromCode(code),
    @Transient override val cause: Throwable? = null,
) : Throwable()
// endregion

