name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: tools/go.mod

      - name: Regenerate examples
        run: |
          go -C tools tool webrpc-gen -schema=../_examples/ClientExample/service.ridl -target=.. -client -okhttpTransport=true -out=../_examples/ClientExample/client/src/main/kotlin/ExampleServiceClient.kt
      - name: Git diff of regenerated files
        run: cd _examples && make diff

      - name: Run generator unit tests
        run: go test ./...

      - name: Run generated client tests
        run: cd Tests && ./RunTests.sh

      - name: Compile example client
        run: cd _examples/ClientExample/client && ./gradlew --no-daemon compileKotlin
